name: Deploy via AWS SSM

on:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
            INSTANCE_ID:
                required: true
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy via AWS SSM
        runs-on: ubuntu-latest
        permissions:
            issues: write

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Run EC2 Command via AWS SSM
              uses: thomasvjoseph/aws-ssm-send@v1.0.0.rc2
              with:
                instance-id: ${{ secrets.INSTANCE_ID }}
                region: ${{ secrets.AWS_REGION }}
                commands: |
                    echo "Hello from GitHub Actions!"
                    echo "Running on instance: ${{ secrets.INSTANCE_ID }}"
                    echo "AWS Region: ${{ secrets.AWS_REGION }}"
                    echo "GitHub Actions Workflow: ${{ github.workflow }}"
                    echo "GitHub Actions Run ID: ${{ github.run_id }}"
                    echo "GitHub Actions Actor: ${{ github.actor }}"