name: Deploy via AWS SSM

on:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
            INSTANCE_ID:
                required: true
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy via AWS SSM
        runs-on: ubuntu-latest
        permissions:
            issues: write

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Execute Deployment Commands via SSM
              run: |
                aws ssm send-command \
                  --document-name "AWS-RunShellScript" \
                  --targets "Key=instanceids,Values=${{ secrets.INSTANCE_ID }}" \
                  --parameters 'commands=[
                    "cd /var/www/html",
                    "git pull",
                    "sudo composer update",
                    "sudo php artisan cache:clear",
                    "sudo php artisan route:clear"
                  ]' \
                  --region ${{ secrets.AWS_REGION }}