name: Deploy via AWS SSM

on:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
            INSTANCE_ID:
                required: true
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
    deploy:
        name: Deploy via AWS SSM
        runs-on: ubuntu-latest
        permissions:
            issues: write

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Debug region
              run: |
               echo "AWS_REGION: {{ env.AWS_REGION }}"

            - name: Run EC2 Command via AWS SSM
              uses: thomasvjoseph/aws-ssm-send@v1.0.0-rc3
              with:
                instance-id: i-0452647ec4ff50524
                region: ap-southeast-1
                commands: |
                    echo "Creating a file..."
                    echo "Hello from GitHub Actions!" > /home/ec2-user/hello.txt
                    cat /home/ssm-user/hello.txt